import os, shutil, subprocess, sys
BASE = r'D:\Seed'

# Delete ALL stale dirs and files
for p in ['src/infra','src/systems','src/bridge','tests/engine','tests/infra','tests/security','tests/systems']:
    d=os.path.join(BASE,p)
    if os.path.exists(d): shutil.rmtree(d,ignore_errors=True)
for p in ['src/engine/EntitySystem.ts','src/engine/Entity.ts','src/engine/ObjectPool.ts','src/engine/PhysicsSystem.ts','src/engine/SpatialIndex.ts','src/engine/Vector3.ts','src/engine/index.ts','src/sdk/EntityFactory.ts','src/sdk/PhysicsConfig.ts','src/sdk/WorldEventListener.ts','src/evaluator/index.ts','src/evaluator/runEvaluation.ts','tests/acoustic.test.ts','tests/event-system.test.ts']:
    f=os.path.join(BASE,p)
    if os.path.exists(f): os.remove(f)

F={}
def w(p,c): F[p]=c

# ===== engine =====
w('src/engine/World.ts', "import { Entity, GameObject } from '../entity/Entity.js';\nimport { EventSystem } from '../event/EventSystem.js';\nimport { WorldTickEvent } from '../event/Event.js';\nexport type SystemState = 'created' | 'running' | 'stopped' | 'error';\nexport interface WorldSystem { readonly name: string; enabled: boolean; start?(): void; stop?(): void; tick(dt: number, world: World, events: EventSystem): void; }\nexport interface WorldConfig { name: string; tickRate: number; }\nexport class World {\n  public readonly config: WorldConfig; public readonly entities = new Map<string, Entity>(); public readonly systems: WorldSystem[] = []; public readonly events = new EventSystem();\n  public worldTime = 0; public tick = 0; public state: SystemState = 'created';\n  constructor(config: WorldConfig) { this.config = config; }\n  addEntity(entity: Entity): this { this.entities.set(entity.id, entity); return this; }\n  removeEntity(id: string): boolean { return this.entities.delete(id); }\n  getEntity(id: string): Entity | undefined { return this.entities.get(id); }\n  addSystem(system: WorldSystem): this { this.systems.push(system); return this; }\n  bodies(): GameObject[] { const out: GameObject[] = []; for (const e of this.entities.values()) if (e instanceof GameObject) out.push(e); return out; }\n  queryByType(type: string): Entity[] { const out: Entity[] = []; for (const e of this.entities.values()) if (e.type === type) out.push(e); return out; }\n  iterate(fn: (e: Entity) => void): void { for (const e of this.entities.values()) fn(e); }\n  start(): void { this.state = 'running'; for (const s of this.systems) s.start?.(); }\n  stop(): void { this.state = 'stopped'; for (const s of this.systems) s.stop?.(); }\n  step(dt: number): void { this.tick++; this.worldTime += dt; this.events.emit(new WorldTickEvent(this.tick, this.worldTime)); for (const s of this.systems) { if (!s.enabled) continue; s.tick(dt, this, this.events); } }\n}\n")

w('src/engine/WorldEngine.ts', "import { World } from './World.js';\nimport { Logger } from '../reliability/Logger.js';\nconst log = Logger.for('engine');\nexport interface EngineOptions { fixedDt?: number; }\nexport class WorldEngine {\n  private world: World | null = null; private timer: NodeJS.Timeout | null = null; private readonly fixedDt: number; private running = false;\n  constructor(opts: EngineOptions = {}) { this.fixedDt = opts.fixedDt ?? 1 / 60; }\n  load(world: World): void { this.world = world; log.info('world loaded', { world: world.config.name, entities: world.entities.size }); }\n  start(): void { if (!this.world) throw new Error('no world loaded'); if (this.running) return; this.running = true; this.world.start(); const dt = 1 / this.world.config.tickRate; this.timer = setInterval(() => this.world?.step(dt), dt * 1000); log.info('engine started', { tickRate: this.world.config.tickRate }); }\n  stop(): void { this.running = false; if (this.timer) { clearInterval(this.timer); this.timer = null; } this.world?.stop(); log.info('engine stopped'); }\n  runTicks(n: number): void { if (!this.world) throw new Error('no world loaded'); const dt = 1 / this.world.config.tickRate; for (let i = 0; i < n; i++) this.world.step(dt); }\n  get isRunning(): boolean { return this.running; }\n  get currentWorld(): World | null { return this.world; }\n}\n")

# ===== entity =====
w('src/entity/Vector3.ts', "import type { IVector3 } from '../types/index.js';\nexport class Vector3 implements IVector3 {\n  public readonly x: number; public readonly y: number; public readonly z: number;\n  constructor(x = 0, y = 0, z = 0) { this.x = x; this.y = y; this.z = z; }\n  static get zero(): Vector3 { return new Vector3(0, 0, 0); }\n  static from(v: { x: number; y: number; z: number }): Vector3 { return new Vector3(v.x, v.y, v.z); }\n  add(v: IVector3): Vector3 { return new Vector3(this.x + v.x, this.y + v.y, this.z + v.z); }\n  sub(v: IVector3): Vector3 { return new Vector3(this.x - v.x, this.y - v.y, this.z - v.z); }\n  mul(s: number): Vector3 { return new Vector3(this.x * s, this.y * s, this.z * s); }\n  div(s: number): Vector3 { if (s === 0) return Vector3.zero; return new Vector3(this.x / s, this.y / s, this.z / s); }\n  dot(v: IVector3): number { return this.x * v.x + this.y * v.y + this.z * v.z; }\n  cross(v: IVector3): Vector3 { return new Vector3(this.y * v.z - this.z * v.y, this.z * v.x - this.x * v.z, this.x * v.y - this.y * v.x); }\n  length(): number { return Math.sqrt(this.x * this.x + this.y * this.y + this.z * this.z); }\n  lengthSquared(): number { return this.x * this.x + this.y * this.y + this.z * this.z; }\n  normalize(): Vector3 { const len = this.length(); if (len === 0) return Vector3.zero; return this.div(len); }\n  distance(v: IVector3): number { return this.sub(v).length(); }\n  distanceSquared(v: IVector3): number { return this.sub(v).lengthSquared(); }\n  lerp(v: IVector3, t: number): Vector3 { const k = clamp(t, 0, 1); return new Vector3(this.x + (v.x - this.x) * k, this.y + (v.y - this.y) * k, this.z + (v.z - this.z) * k); }\n  clamp(min: number, max: number): Vector3 { return new Vector3(clamp(this.x, min, max), clamp(this.y, min, max), clamp(this.z, min, max)); }\n  distanceTo(v: IVector3): number { return this.distance(v); }\n  clone(): Vector3 { return new Vector3(this.x, this.y, this.z); }\n  equals(v: IVector3): boolean { return this.x === v.x && this.y === v.y && this.z === v.z; }\n  toArray(): [number, number, number] { return [this.x, this.y, this.z]; }\n  toObject(): { x: number; y: number; z: number } { return { x: this.x, y: this.y, z: this.z }; }\n  toString(): string { return `Vector3(${this.x.toFixed(3)}, ${this.y.toFixed(3)}, ${this.z.toFixed(3)})`; }\n}\nexport function clamp(value: number, min: number, max: number): number { if (Number.isNaN(value)) return min; if (value < min) return min; if (value > max) return max; return value; }\n")

w('src/entity/Entity.ts', "import { Vector3 } from './Vector3.js';\nimport type { EntityType, IVector3 } from '../types/index.js';\nlet nextEntityId = 1;\nfunction genId(prefix: string): string { return `${prefix}_${Date.now().toString(36)}_${(nextEntityId++).toString(36)}`; }\nexport class Entity {\n  public readonly id: string; public name: string; public readonly type: EntityType;\n  public position: Vector3; public velocity: Vector3; public mass: number; public material: string;\n  public readonly state: Map<string, unknown>; public readonly properties: Map<string, unknown>;\n  public active: boolean; public readonly createdAt: number;\n  public readonly children: Entity[] = []; public parent: Entity | null = null;\n  constructor(opts: { id?: string; name: string; type: EntityType; position?: IVector3; velocity?: IVector3; mass?: number; material?: string; }) {\n    this.id = opts.id ?? genId('ent'); this.name = opts.name; this.type = opts.type;\n    this.position = Vector3.from(opts.position ?? { x: 0, y: 0, z: 0 });\n    this.velocity = Vector3.from(opts.velocity ?? { x: 0, y: 0, z: 0 });\n    this.mass = opts.mass ?? 1; this.material = opts.material ?? 'default';\n    this.state = new Map(); this.properties = new Map(); this.active = true; this.createdAt = Date.now();\n  }\n  attach(child: Entity): void { if (child.parent === this) return; child.detach(); this.children.push(child); child.parent = this; }\n  detach(): void { if (this.parent) { const idx = this.parent.children.indexOf(this); if (idx >= 0) this.parent.children.splice(idx, 1); this.parent = null; } }\n  walk(fn: (e: Entity) => void): void { fn(this); for (const c of this.children) c.walk(fn); }\n  toJSON(): Record<string, unknown> { return { id: this.id, name: this.name, type: this.type, position: this.position.toObject(), velocity: this.velocity.toObject(), mass: this.mass, material: this.material, active: this.active, createdAt: this.createdAt, children: this.children.map((c) => c.id), properties: Object.fromEntries(this.properties), state: Object.fromEntries(this.state) }; }\n}\nexport class GameObject extends Entity {\n  public halfExtents: Vector3; public interactable: boolean; public hittable: boolean;\n  constructor(opts: { id?: string; name: string; type?: EntityType; position?: IVector3; velocity?: IVector3; mass?: number; material?: string; halfExtents?: IVector3; interactable?: boolean; hittable?: boolean; }) {\n    super({ ...opts, type: opts.type ?? 'dynamic' });\n    this.halfExtents = Vector3.from(opts.halfExtents ?? { x: 0.5, y: 0.5, z: 0.5 });\n    this.interactable = opts.interactable ?? false; this.hittable = opts.hittable ?? true;\n  }\n  aabbMin(): Vector3 { return this.position.sub(this.halfExtents); }\n  aabbMax(): Vector3 { return this.position.add(this.halfExtents); }\n}\n")

w('src/entity/EntityFactory.ts', "import { GameObject } from './Entity.js';\nimport { Vector3 } from './Vector3.js';\nimport type { IVector3 } from '../types/index.js';\nexport class EntityFactory {\n  static staticBox(name: string, center: IVector3, halfExtents: IVector3): GameObject { return new GameObject({ name, type: 'static', position: center, velocity: { x: 0, y: 0, z: 0 }, mass: Number.POSITIVE_INFINITY, material: 'stone', halfExtents, interactable: true, hittable: true }); }\n  static dynamicBox(opts: { name: string; position: IVector3; mass?: number; material?: string; velocity?: IVector3; halfExtents?: IVector3; }): GameObject { return new GameObject({ name: opts.name, type: 'dynamic', position: opts.position, velocity: opts.velocity ?? { x: 0, y: 0, z: 0 }, mass: opts.mass ?? 1, material: opts.material ?? 'wood', halfExtents: opts.halfExtents ?? { x: 0.5, y: 0.5, z: 0.5 }, interactable: true, hittable: true }); }\n  static zoneTrigger(opts: { name: string; center: IVector3; halfExtents: IVector3; onEnter?: (entityId: string) => void; }): GameObject { const zone = new GameObject({ name: opts.name, type: 'trigger', position: opts.center, halfExtents: opts.halfExtents, mass: 0, material: 'zone', interactable: false, hittable: false }); zone.properties.set('isZone', true); zone.properties.set('onEnter', opts.onEnter); return zone; }\n  static soulProxy(opts: { soulId: string; name: string; element: string; position?: IVector3; }): GameObject { const proxy = new GameObject({ id: `soul_${opts.soulId}`, name: opts.name, type: 'soul-proxy', position: opts.position ?? { x: 0, y: 1, z: 0 }, mass: 5, material: `soul:${opts.element}`, halfExtents: { x: 0.4, y: 0.8, z: 0.4 }, interactable: true, hittable: true }); proxy.properties.set('soulId', opts.soulId); proxy.properties.set('element', opts.element); proxy.state.set('insideWorld', true); return proxy; }\n  static distance(a: IVector3, b: IVector3): number { return Vector3.from(a).distance(b); }\n}\n")

print(f'Phase A: {len(F)} files')
for rel,content in F.items():
    full=os.path.join(BASE,rel)
    os.makedirs(os.path.dirname(full),exist_ok=True)
    with open(full,'w',encoding='utf-8',newline='\n') as f: f.write(content)
print('Phase A written')
