import os, shutil
BASE = r'D:\Seed'
for p in ['src/bridge']:
    d=os.path.join(BASE,p)
    if os.path.exists(d): shutil.rmtree(d,ignore_errors=True)

F={}
def w(p,c): F[p]=c

w('src/sdk/WorldBuilder.ts', "// WorldBuilder: fluent SDK for constructing a World.\nimport { World, type WorldSystem } from '../engine/World.js';\nimport type { Entity } from '../entity/Entity.js';\nimport { PhysicsSystem } from '../physics/PhysicsSystem.js';\nimport { PhysicsConfig } from '../physics/PhysicsConfig.js';\nexport class WorldBuilder {\n  private world: World;\n  private physics: PhysicsSystem | null = null;\n  constructor(name = 'unnamed-world') { this.world = new World({ name, tickRate: 60 }); }\n  setConfig(cfg: Partial<{ name: string; tickRate: number }>): this { this.world.config.name = cfg.name ?? this.world.config.name; this.world.config.tickRate = cfg.tickRate ?? this.world.config.tickRate; return this; }\n  addEntity(entity: Entity): this { this.world.addEntity(entity); return this; }\n  addSystem(system: WorldSystem): this { this.world.addSystem(system); return this; }\n  usePhysics(config: PhysicsConfig = PhysicsConfig.defaults()): this { this.physics = new PhysicsSystem({ config }); this.world.addSystem(this.physics); return this; }\n  build(): World { return this.world; }\n  get physicsSystem(): PhysicsSystem | null { return this.physics; }\n}\n")

w('src/sdk/index.ts', "// SDK barrel: the public surface of Seed.\nexport { WorldBuilder } from './WorldBuilder.js';\nexport { EntityFactory } from '../entity/EntityFactory.js';\nexport { PhysicsConfig, PhysicsConfigBuilder } from '../physics/PhysicsConfig.js';\nexport { PhysicsSystem } from '../physics/PhysicsSystem.js';\nexport { AcousticPropagation } from '../communication/AcousticPropagation.js';\nexport { NetworkPacket } from '../communication/NetworkPacket.js';\nexport { WorldResonance } from '../communication/WorldResonance.js';\nexport { Message } from '../communication/Message.js';\nexport type { ReceivedMessage } from '../communication/Message.js';\nexport type { CommunicationStrategy, WorldView } from '../communication/CommunicationStrategy.js';\n")

w('src/security/InputValidator.ts', "// InputValidator: tiny schema-based validator.\nexport type FieldType = 'string' | 'number' | 'boolean' | 'object' | 'array';\nexport interface FieldRule { type: FieldType; required?: boolean; min?: number; max?: number; enum?: Array<string | number | boolean>; pattern?: RegExp; }\nexport type Schema = Record<string, FieldRule>;\nexport interface ValidationResult { ok: boolean; errors: string[]; value: Record<string, unknown>; }\nexport class InputValidator {\n  validate(schema: Schema, input: unknown): ValidationResult {\n    const errors: string[] = []; const value: Record<string, unknown> = {};\n    if (typeof input !== 'object' || input === null || Array.isArray(input)) return { ok: false, errors: ['input must be an object'], value: {} };\n    const obj = input as Record<string, unknown>;\n    for (const [field, rule] of Object.entries(schema)) {\n      const raw = obj[field];\n      if (raw === undefined || raw === null) { if (rule.required) errors.push(`\"${field}\" is required`); continue; }\n      if (!this.checkType(field, raw, rule.type, errors)) continue;\n      if (rule.type === 'string' && typeof raw === 'string') { if (rule.min !== undefined && raw.length < rule.min) errors.push(`\"${field}\" too short`); if (rule.max !== undefined && raw.length > rule.max) errors.push(`\"${field}\" too long`); if (rule.pattern && !rule.pattern.test(raw)) errors.push(`\"${field}\" failed pattern`); }\n      if (rule.type === 'number' && typeof raw === 'number') { if (rule.min !== undefined && raw < rule.min) errors.push(`\"${field}\" below min`); if (rule.max !== undefined && raw > rule.max) errors.push(`\"${field}\" above max`); }\n      if (rule.enum !== undefined && !rule.enum.includes(raw as string | number | boolean)) errors.push(`\"${field}\" not in allowed set`);\n      value[field] = raw;\n    }\n    return { ok: errors.length === 0, errors, value };\n  }\n  private checkType(field: string, raw: unknown, type: FieldType, errors: string[]): boolean {\n    switch (type) {\n      case 'string': if (typeof raw !== 'string') { errors.push(`\"${field}\" must be a string`); return false; } return true;\n      case 'number': if (typeof raw !== 'number' || Number.isNaN(raw)) { errors.push(`\"${field}\" must be a number`); return false; } return true;\n      case 'boolean': if (typeof raw !== 'boolean') { errors.push(`\"${field}\" must be a boolean`); return false; } return true;\n      case 'object': if (typeof raw !== 'object' || raw === null || Array.isArray(raw)) { errors.push(`\"${field}\" must be an object`); return false; } return true;\n      case 'array': if (!Array.isArray(raw)) { errors.push(`\"${field}\" must be an array`); return false; } return true;\n    }\n  }\n}\n")

w('src/security/PermissionSystem.ts', "// PermissionSystem: role-based access control.\nimport type { Role } from '../types/index.js';\nexport interface PermissionRule { role: Role; resource: string; action: string; }\nexport class PermissionSystem {\n  private readonly rules: PermissionRule[] = [];\n  constructor() { this.grant({ role: 'admin', resource: '*', action: '*' }); this.grant({ role: 'observer', resource: '*', action: 'read' }); this.grant({ role: 'soul', resource: 'entity', action: 'read' }); this.grant({ role: 'soul', resource: 'entity', action: 'interact' }); this.grant({ role: 'soul', resource: 'soul', action: 'self-action' }); }\n  grant(rule: PermissionRule): void { this.rules.push(rule); }\n  isAllowed(role: Role, resource: string, action: string): boolean { return this.rules.some((r) => r.role === role && (r.resource === '*' || r.resource === resource) && (r.action === '*' || r.action === action)); }\n  ensure(role: Role, resource: string, action: string): void { if (!this.isAllowed(role, resource, action)) throw new Error(`permission denied: ${role} cannot ${action} on ${resource}`); }\n}\n")

w('src/security/RateLimiter.ts', "// RateLimiter: fixed-window per-client limiter.\nexport interface RateLimitResult { allowed: boolean; remaining: number; retryAfterMs: number; }\nexport class RateLimiter {\n  private readonly windows = new Map<string, { windowStart: number; count: number }>();\n  constructor(private readonly qps: number, private readonly windowMs = 1000) {}\n  check(clientId: string, now = Date.now()): RateLimitResult {\n    const existing = this.windows.get(clientId);\n    if (!existing || now - existing.windowStart >= this.windowMs) { this.windows.set(clientId, { windowStart: now, count: 1 }); return { allowed: true, remaining: this.qps - 1, retryAfterMs: 0 }; }\n    if (existing.count < this.qps) { existing.count++; return { allowed: true, remaining: this.qps - existing.count, retryAfterMs: 0 }; }\n    return { allowed: false, remaining: 0, retryAfterMs: this.windowMs - (now - existing.windowStart) };\n  }\n  reset(): void { this.windows.clear(); }\n}\n")

print(f'Writing {len(F)} files...')
for rel,content in F.items():
    full=os.path.join(BASE,rel)
    os.makedirs(os.path.dirname(full),exist_ok=True)
    with open(full,'w',encoding='utf-8',newline='\n') as f: f.write(content)
print('DONE p2')
